// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYY3VAEXC5S003XoZYatVwvzCfAWeR-Ro',
    appId: '1:152130050803:web:4633c189801058878d7586',
    messagingSenderId: '152130050803',
    projectId: 'do-an-cuoi-ky-24f89',
    authDomain: 'do-an-cuoi-ky-24f89.firebaseapp.com',
    storageBucket: 'do-an-cuoi-ky-24f89.firebasestorage.app',
    measurementId: 'G-CQH07EDDLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Yxfr7LPyFEGlcmSOZiUPxQHULhu47w0',
    appId: '1:152130050803:android:1459db570de2e8488d7586',
    messagingSenderId: '152130050803',
    projectId: 'do-an-cuoi-ky-24f89',
    storageBucket: 'do-an-cuoi-ky-24f89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCfKVNYN9EnnD57-pra3tlFQGl8UW0ZN0',
    appId: '1:152130050803:ios:2b50ebb5f97d39c58d7586',
    messagingSenderId: '152130050803',
    projectId: 'do-an-cuoi-ky-24f89',
    storageBucket: 'do-an-cuoi-ky-24f89.firebasestorage.app',
    iosBundleId: 'com.example.smsOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCfKVNYN9EnnD57-pra3tlFQGl8UW0ZN0',
    appId: '1:152130050803:ios:2b50ebb5f97d39c58d7586',
    messagingSenderId: '152130050803',
    projectId: 'do-an-cuoi-ky-24f89',
    storageBucket: 'do-an-cuoi-ky-24f89.firebasestorage.app',
    iosBundleId: 'com.example.smsOtp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYY3VAEXC5S003XoZYatVwvzCfAWeR-Ro',
    appId: '1:152130050803:web:8978f1e5dfe1aabf8d7586',
    messagingSenderId: '152130050803',
    projectId: 'do-an-cuoi-ky-24f89',
    authDomain: 'do-an-cuoi-ky-24f89.firebaseapp.com',
    storageBucket: 'do-an-cuoi-ky-24f89.firebasestorage.app',
    measurementId: 'G-FC0P1DTE41',
  );
}
